"use client";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 24, fontSize: 12 },
  h1: { fontSize: 18, marginBottom: 12 },
  grid: { display: "flex", flexDirection: "row", gap: 16 },
  card: { padding: 12, border: "1px solid #000", marginBottom: 8 }
});

export default function ComplianceReport({ data }:{
  data: { totalCalls:number; estimatedCostUsd:number; avgLatencyMs:number; hallucinationRate:number; failures:number; euAiActRisk:string }
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.h1}>AI Governance Compliance Report</Text>
        <View style={styles.grid}>
          <View style={styles.card}><Text>Total Calls: {data.totalCalls}</Text></View>
          <View style={styles.card}><Text>Est. Cost: ${data.estimatedCostUsd.toFixed(4)}</Text></View>
        </View>
        <View style={styles.grid}>
          <View style={styles.card}><Text>Avg Latency: {data.avgLatencyMs} ms</Text></View>
          <View style={styles.card}><Text>Hallucination Rate: {(data.hallucinationRate*100).toFixed(2)}%</Text></View>
          <View style={styles.card}><Text>Failures: {data.failures}</Text></View>
        </View>
        <View style={styles.card}><Text>EU AI Act Risk Category: {data.euAiActRisk}</Text></View>
        <Text>Generated by SentinelAI</Text>
      </Page>
    </Document>
  );
}
